agents-common/src/main/java/org/apache/ranger/plugin/util/RangerRolesProvider.java

Fix PMD Violation
mvn clean install
mvn verify

RANGER-4114: Remove unused import

---

.asf.yaml

Current .asf.yaml notification settings for ranger.git can be viewed at: https://gitbox.apache.org/schemes.cgi?ranger.
The review changes the settings, adds branch protection on master and fixes the labels.
Reviewed guidelines at https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features
Some settings can only be tested on master.

RANGER-4116: Add notifications settings, master branch protection and labels

---

intg/src/main/python/README.md

Updating python client README
Skipped, regular build only.

RANGER-4158: Update README.md

---

intg/src/main/python/README.md
intg/src/main/python/setup.py

Changes to initiate a new version of python client on [pypi.org](https://pypi.org/project/apache-ranger/)  
Tested the changes with version 0.0.21 on [test.pypi.org ](https://test.pypi.org/project/apache-ranger/)  
* Uploaded the artifacts as version 0.0.21
* Downloaded and tested the 2 new client apis with python3.

RANGER-4230: Upload version 0.0.11 to PyPI

---

.github/workflows/maven.yml
pom.xml

Enable JDK 11 builds on master and PRs.
All checks have completed with tests on JDK 8 and 11.

RANGER-4752: Enable jdk 11 builds on PRs and merges to master

---

ranger-tools/src/main/python/stress/stress-hbase-loadgenerator.py

Add license 
mvn clean install

RANGER-4761: Add License

---

agents-common/src/test/resources/policyengine/test_policyengine_atlas.json

1) Service def for atlas test cases
2) Resource structure for atlas for test cases fixed
1) New test case added for checking base case for atlas policy evaluation. 
2) Existing atlas test cases passed after changes

RANGER-4829: Atlas policy engine unit tests fixes

---

ranger-tools/src/main/python/requirements.txt

Collating few PR's from dependabot
* https://github.com/apache/ranger/pull/323 (idna)
* https://github.com/apache/ranger/pull/324 (jinja2)
* https://github.com/apache/ranger/pull/325 (urllib3)

RANGER-4849: Bump python dependencies in ranger-tools module

---

security-admin/src/main/java/org/apache/ranger/biz/XUserMgr.java

(cherry picked from commit 5315d8ba14653c545e99e7cb61e7436b93387f63)

RANGER-4074: Fix x_user_module_perm entry creation with NULL module Id (#222)

---

.github/workflows/maven.yml

RANGER-4921: Update docker compose command in CI

---

tagsync/src/main/java/org/apache/ranger/tagsync/source/atlas/AtlasOzoneResourceMapper.java

…. Configurable if required.
OFS and O3FS keys - isRecursive should be enabled by default.
Exanmple: When a tag is applied to the key k1 then same tag should be applied to k1/k2
These properties are configurable to deal with backward compatibility scenarios.
Refactoring for better readability
Existing Unit tests pass
Manual tests in cluster

RANGER-4914: Tagsync ozone - isRecursive=true for both ofs and o3fs keys by default

---

dev-support/ranger-docker/README.md
dev-support/ranger-docker/download-archives.sh

Retain behavior of downloading all archives when no argument is passed.
Tested the following:
- ./download-archives.sh 
- ./download-archives.sh hadoop ozone

RANGER-3801: Download all archives when no arg is passed and update docker README

---

.github/workflows/maven.yml

Potential fix for RANGER-4951.
CI passed

RANGER-4951: Prune docker cache before docker-build

---

agents-common/src/main/java/org/apache/ranger/plugin/policyengine/RangerPolicyEngineImpl.java

Fix compilation failure
mvn clean compile

RANGER-5001: Resolve merge conflicts to fix compilation failure

---

intg/pom.xml
intg/src/main/java/org/apache/ranger/RangerClient.java
intg/src/main/java/org/apache/ranger/RangerServiceException.java
intg/src/test/java/org/apache/ranger/TestRangerClient.java

Updated `intg` module sources to comply with the check-style requirements.

RANGER-5033: checkstyle compliance updates - intg

---

plugin-kudu/pom.xml
plugin-kudu/src/main/java/org/apache/ranger/services/kudu/RangerServiceKudu.java

Updated `plugin-kudu` module sources to comply with the check-style requirements.

RANGER-5041: checkstyle compliance updates - plugin-kudu

---

ranger-authn/pom.xml
ranger-authn/src/main/java/org/apache/ranger/authz/handler/RangerAuth.java
ranger-authn/src/main/java/org/apache/ranger/authz/handler/RangerAuthHandler.java
ranger-authn/src/main/java/org/apache/ranger/authz/handler/jwt/RangerDefaultJwtAuthHandler.java
ranger-authn/src/main/java/org/apache/ranger/authz/handler/jwt/RangerJwtAuthHandler.java

Updated `ranger-authn` module sources to comply with the check-style requirements.

RANGER-5054: checkstyle compliance updates - ranger-authn

---

plugin-nifi-registry/pom.xml
plugin-nifi-registry/src/main/java/org/apache/ranger/services/nifi/registry/RangerServiceNiFiRegistry.java
plugin-nifi-registry/src/main/java/org/apache/ranger/services/nifi/registry/client/NiFiRegistryAuthType.java
plugin-nifi-registry/src/main/java/org/apache/ranger/services/nifi/registry/client/NiFiRegistryClient.java
plugin-nifi-registry/src/main/java/org/apache/ranger/services/nifi/registry/client/NiFiRegistryConfigs.java
plugin-nifi-registry/src/main/java/org/apache/ranger/services/nifi/registry/client/NiFiRegistryConnectionMgr.java
plugin-nifi-registry/src/test/java/org/apache/ranger/services/nifi/registry/client/TestNiFiRegistryClient.java
plugin-nifi-registry/src/test/java/org/apache/ranger/services/nifi/registry/client/TestNiFiRegistryConnectionMgr.java

Updated `plugin-nifi-registry` module sources to comply with the check-style requirements.

RANGER-5044: checkstyle compliance updates - plugin-nifi-registry

---

ranger-metrics/pom.xml
ranger-metrics/src/main/java/org/apache/ranger/metrics/RangerMetricsSystemWrapper.java
ranger-metrics/src/main/java/org/apache/ranger/metrics/sink/RangerMetricsJsonSink.java
ranger-metrics/src/main/java/org/apache/ranger/metrics/sink/RangerMetricsPrometheusSink.java
ranger-metrics/src/main/java/org/apache/ranger/metrics/source/RangerMetricsContainerSource.java
ranger-metrics/src/main/java/org/apache/ranger/metrics/source/RangerMetricsJvmSource.java
ranger-metrics/src/main/java/org/apache/ranger/metrics/source/RangerMetricsSource.java
ranger-metrics/src/main/java/org/apache/ranger/metrics/wrapper/RangerMetricsSinkWrapper.java
ranger-metrics/src/test/java/org/apache/ranger/metrics/source/TestRangerMetricsContainerSource.java

Updated `ranger-metrics` module sources to comply with the check-style requirements.

RANGER-5057: checkstyle compliance updates - ranger-metrics

---

pom.xml

`ranger-nestedstructure-plugin` is not built on Linux, because it is not part of the `linux` profile.
This can be reproduced simply on Linux by running `mvn clean`.  The plugin is not part of the build.
```
$ mvn clean | grep -i nested | wc -l
0
```
`distro` still depends on it.  This causes CI to try to download it from remote repo (since CI runs on Linux).
```
[ERROR] Failed to execute goal on project ranger-distro: Could not resolve dependencies for project org.apache.ranger:ranger-distro:jar:3.0.0-SNAPSHOT: Failed to collect dependencies at org.apache.ranger:ranger-nestedstructure-plugin:jar:3.0.0-SNAPSHOT: Failed to read artifact descriptor for org.apache.ranger:ranger-nestedstructure-plugin:jar:3.0.0-SNAPSHOT: Could not transfer artifact …
```

RANGER-5067. ranger-nestedstructure-plugin is not built on linux

---

.github/workflows/maven.yml

Add timeouts to jobs in CI
CI Run 2 successful with timeout of 15 mins.

RANGER-5021: Add timeouts to jobs in CI

---

pom.xml

Added dependent modules for kms and security-admin to appropriate profiles
Verified that build with unit tests succeed

RANGER-5070: update profiles to include dependent modules for kms and security-admin

---

plugin-nestedstructure/pom.xml
plugin-nestedstructure/src/main/java/org/apache/ranger/authorization/nestedstructure/authorizer/AccessResult.java
plugin-nestedstructure/src/main/java/org/apache/ranger/authorization/nestedstructure/authorizer/DataMasker.java
plugin-nestedstructure/src/main/java/org/apache/ranger/authorization/nestedstructure/authorizer/FieldLevelAccess.java
plugin-nestedstructure/src/main/java/org/apache/ranger/authorization/nestedstructure/authorizer/JsonManipulator.java
plugin-nestedstructure/src/main/java/org/apache/ranger/authorization/nestedstructure/authorizer/MaskTypes.java
plugin-nestedstructure/src/main/java/org/apache/ranger/authorization/nestedstructure/authorizer/MaskingException.java
plugin-nestedstructure/src/main/java/org/apache/ranger/authorization/nestedstructure/authorizer/NestedStructureAccessType.java
plugin-nestedstructure/src/main/java/org/apache/ranger/authorization/nestedstructure/authorizer/NestedStructureAuditHandler.java
plugin-nestedstructure/src/main/java/org/apache/ranger/authorization/nestedstructure/authorizer/NestedStructureAuthorizer.java
plugin-nestedstructure/src/main/java/org/apache/ranger/authorization/nestedstructure/authorizer/NestedStructureResource.java
plugin-nestedstructure/src/main/java/org/apache/ranger/authorization/nestedstructure/authorizer/NestedStructureService.java
plugin-nestedstructure/src/main/java/org/apache/ranger/authorization/nestedstructure/authorizer/RecordFilterJavaScript.java
plugin-nestedstructure/src/test/java/org/apache/ranger/authorization/nestedstructure/authorizer/ExampleClient.java
plugin-nestedstructure/src/test/java/org/apache/ranger/authorization/nestedstructure/authorizer/TestDataMasker.java
plugin-nestedstructure/src/test/java/org/apache/ranger/authorization/nestedstructure/authorizer/TestJsonManipulator.java
plugin-nestedstructure/src/test/java/org/apache/ranger/authorization/nestedstructure/authorizer/TestNestedStructureAuthorizer.java
plugin-nestedstructure/src/test/java/org/apache/ranger/authorization/nestedstructure/authorizer/TestRecordFilterJavaScript.java

Updated `plugin nested-structure module` sources to comply with the check-style requirements.

RANGER-5043: checkstyle compliance updates - plugin-nestedstructure module

---

storm-agent/pom.xml
storm-agent/src/main/java/org/apache/ranger/authorization/storm/StormRangerPlugin.java
storm-agent/src/main/java/org/apache/ranger/authorization/storm/authorizer/RangerStormAuthorizer.java
storm-agent/src/main/java/org/apache/ranger/services/storm/RangerServiceStorm.java
storm-agent/src/main/java/org/apache/ranger/services/storm/client/StormClient.java
storm-agent/src/main/java/org/apache/ranger/services/storm/client/StormConnectionMgr.java
storm-agent/src/main/java/org/apache/ranger/services/storm/client/StormResourceMgr.java
storm-agent/src/main/java/org/apache/ranger/services/storm/client/json/model/Topology.java
storm-agent/src/main/java/org/apache/ranger/services/storm/client/json/model/TopologyListResponse.java
storm-agent/src/test/java/org/apache/ranger/authorization/storm/RangerAdminClientImpl.java
storm-agent/src/test/java/org/apache/ranger/authorization/storm/StormRangerAuthorizerTest.java
storm-agent/src/test/java/org/apache/ranger/authorization/storm/WordCounterBolt.java
storm-agent/src/test/java/org/apache/ranger/authorization/storm/WordSpout.java

Updated `storm module` sources to comply with the check-style requirements.

RANGER-5062: checkstyle compliance updates - storm module

---

dev-support/checkstyle-suppressions.xml
plugin-yarn/pom.xml
plugin-yarn/src/main/java/org/apache/ranger/authorization/yarn/authorizer/RangerYarnAuthorizer.java
plugin-yarn/src/main/java/org/apache/ranger/services/yarn/RangerServiceYarn.java
plugin-yarn/src/main/java/org/apache/ranger/services/yarn/client/YarnClient.java
plugin-yarn/src/main/java/org/apache/ranger/services/yarn/client/YarnConnectionMgr.java
plugin-yarn/src/main/java/org/apache/ranger/services/yarn/client/YarnResourceMgr.java
plugin-yarn/src/main/java/org/apache/ranger/services/yarn/client/json/model/YarnSchedulerResponse.java

Updated `plugin-yarn module` sources to comply with the check-style requirements.

RANGER-5052: checkstyle compliance updates - plugin-yarn module

---

hive-agent/pom.xml
hive-agent/src/main/java/com/xasecure/authorization/hive/authorizer/XaSecureHiveAuthorizerFactory.java
hive-agent/src/main/java/org/apache/ranger/authorization/hive/authorizer/RangerHiveAccessRequest.java
hive-agent/src/main/java/org/apache/ranger/authorization/hive/authorizer/RangerHiveAuditHandler.java
hive-agent/src/main/java/org/apache/ranger/authorization/hive/authorizer/RangerHiveAuthorizer.java
hive-agent/src/main/java/org/apache/ranger/authorization/hive/authorizer/RangerHiveAuthorizerBase.java
hive-agent/src/main/java/org/apache/ranger/authorization/hive/authorizer/RangerHiveAuthorizerFactory.java
hive-agent/src/main/java/org/apache/ranger/authorization/hive/authorizer/RangerHivePolicyProvider.java
hive-agent/src/main/java/org/apache/ranger/authorization/hive/authorizer/RangerHiveResource.java
hive-agent/src/main/java/org/apache/ranger/authorization/hive/authorizer/RangerHiveResourceACLs.java
hive-agent/src/main/java/org/apache/ranger/authorization/hive/constants/RangerHiveConstants.java
hive-agent/src/main/java/org/apache/ranger/services/hive/RangerServiceHive.java
hive-agent/src/main/java/org/apache/ranger/services/hive/client/HiveClient.java
hive-agent/src/main/java/org/apache/ranger/services/hive/client/HiveConnectionMgr.java
hive-agent/src/main/java/org/apache/ranger/services/hive/client/HiveResourceMgr.java
hive-agent/src/test/java/org/apache/ranger/services/hive/HIVERangerAuthorizerTest.java
hive-agent/src/test/java/org/apache/ranger/services/hive/RangerAdminClientImpl.java
hive-agent/src/test/java/org/apache/ranger/services/hive/RangerHiveOperationType.java
hive-agent/src/test/java/org/apache/ranger/services/hive/TestAllHiveOperationInRanger.java

updated hive-agent sources to be compliant with checkstyle requirements introduced in RANGER-5017
Verified that build with unit tests complete successfully

RANGER-5032: checkstyle compliance updates - hive-agent

---

plugin-solr/pom.xml
plugin-solr/src/main/java/org/apache/ranger/authorization/solr/authorizer/FieldToAttributeMapping.java
plugin-solr/src/main/java/org/apache/ranger/authorization/solr/authorizer/RangerSolrAuditHandler.java
plugin-solr/src/main/java/org/apache/ranger/authorization/solr/authorizer/RangerSolrAuthorizer.java
plugin-solr/src/main/java/org/apache/ranger/authorization/solr/authorizer/SolrAuthzUtil.java
plugin-solr/src/main/java/org/apache/ranger/authorization/solr/authorizer/SubsetQueryPlugin.java
plugin-solr/src/main/java/org/apache/ranger/services/solr/RangerServiceSolr.java
plugin-solr/src/main/java/org/apache/ranger/services/solr/RangerSolrConstants.java
plugin-solr/src/main/java/org/apache/ranger/services/solr/client/ServiceSolrClient.java
plugin-solr/src/main/java/org/apache/ranger/services/solr/client/ServiceSolrConnectionMgr.java

Updated `plugin-solr module` sources to comply with the check-style requirements.

RANGER-5049: checkstyle compliance updates - plugin-solr module

---

plugin-atlas/pom.xml
plugin-atlas/src/main/java/org/apache/ranger/authorization/atlas/authorizer/RangerAtlasAuthorizer.java
plugin-atlas/src/main/java/org/apache/ranger/services/atlas/RangerServiceAtlas.java
plugin-atlas/src/main/java/org/apache/ranger/services/atlas/json/model/ResourceEntityResponse.java
plugin-atlas/src/main/java/org/apache/ranger/services/atlas/json/model/ResourceOperationResponse.java
plugin-atlas/src/main/java/org/apache/ranger/services/atlas/json/model/ResourceTaxonomyResponse.java
plugin-atlas/src/main/java/org/apache/ranger/services/atlas/json/model/ResourceTermResponse.java
plugin-atlas/src/main/java/org/apache/ranger/services/atlas/json/model/ResourceTypeResponse.java

Updated plugin-atlas module to be compliant with checkstyle requirements
Verified that build with unit tests complete successfully

RANGER-5037: checkstyle compliance updates - plugin-atlas

---

plugin-nifi/pom.xml
plugin-nifi/src/main/java/org/apache/ranger/services/nifi/RangerServiceNiFi.java
plugin-nifi/src/main/java/org/apache/ranger/services/nifi/client/NiFiAuthType.java
plugin-nifi/src/main/java/org/apache/ranger/services/nifi/client/NiFiClient.java
plugin-nifi/src/main/java/org/apache/ranger/services/nifi/client/NiFiConfigs.java
plugin-nifi/src/main/java/org/apache/ranger/services/nifi/client/NiFiConnectionMgr.java
plugin-nifi/src/test/java/org/apache/ranger/services/nifi/client/TestNiFiClient.java
plugin-nifi/src/test/java/org/apache/ranger/services/nifi/client/TestNiFiConnectionMgr.java

Updated `plugin-nifi module` sources to comply with the check-style requirements.

RANGER-5045: checkstyle compliance updates - plugin-nifi module

---

plugin-kafka/pom.xml
plugin-kafka/src/main/java/org/apache/ranger/authorization/kafka/authorizer/RangerKafkaAuditHandler.java
plugin-kafka/src/main/java/org/apache/ranger/authorization/kafka/authorizer/RangerKafkaAuthorizer.java
plugin-kafka/src/main/java/org/apache/ranger/services/kafka/RangerServiceKafka.java
plugin-kafka/src/main/java/org/apache/ranger/services/kafka/client/ServiceKafkaClient.java
plugin-kafka/src/main/java/org/apache/ranger/services/kafka/client/ServiceKafkaConnectionMgr.java
plugin-kafka/src/test/java/org/apache/ranger/authorization/kafka/authorizer/KafkaRangerAuthorizerGSSTest.java
plugin-kafka/src/test/java/org/apache/ranger/authorization/kafka/authorizer/KafkaRangerAuthorizerSASLSSLTest.java
plugin-kafka/src/test/java/org/apache/ranger/authorization/kafka/authorizer/KafkaRangerAuthorizerTest.java
plugin-kafka/src/test/java/org/apache/ranger/authorization/kafka/authorizer/KafkaRangerTopicCreationTest.java
plugin-kafka/src/test/java/org/apache/ranger/authorization/kafka/authorizer/KafkaTestUtils.java
plugin-kafka/src/test/java/org/apache/ranger/authorization/kafka/authorizer/RangerAdminClientImpl.java

Updated `plugin-kafka module` sources to comply with the check-style requirements.

RANGER-5039: checkstyle compliance updates - plugin-kafka module

---

plugin-kms/pom.xml
plugin-kms/src/main/java/org/apache/ranger/authorization/kms/authorizer/RangerKMSAccessRequest.java
plugin-kms/src/main/java/org/apache/ranger/authorization/kms/authorizer/RangerKMSPlugin.java
plugin-kms/src/main/java/org/apache/ranger/authorization/kms/authorizer/RangerKMSResource.java
plugin-kms/src/main/java/org/apache/ranger/authorization/kms/authorizer/RangerKmsAuthorizer.java
plugin-kms/src/main/java/org/apache/ranger/services/kms/RangerServiceKMS.java
plugin-kms/src/main/java/org/apache/ranger/services/kms/client/KMSClient.java
plugin-kms/src/main/java/org/apache/ranger/services/kms/client/KMSConnectionMgr.java
plugin-kms/src/main/java/org/apache/ranger/services/kms/client/KMSResourceMgr.java
plugin-kms/src/main/java/org/apache/ranger/services/kms/client/json/model/KMSSchedulerResponse.java
plugin-kms/src/test/java/org/apache/ranger/authorization/kms/authorizer/DerbyTestUtils.java
plugin-kms/src/test/java/org/apache/ranger/authorization/kms/authorizer/RangerAdminClientImpl.java
plugin-kms/src/test/java/org/apache/ranger/authorization/kms/authorizer/RangerKmsAuthorizerTest.java

Only code formatting and code cleanup was done. Also concatenated logger statements were updated by parameterized loggers.
There are no functional changes.
module build  (mvn clean install) passed.

RANGER-5040 : plugin-kms module: update for code readability improvement

---

agents-common/src/main/java/org/apache/ranger/authorization/hadoop/config/RangerPluginConfig.java
plugin-kafka/src/main/java/org/apache/ranger/authorization/kafka/authorizer/RangerKafkaAuthorizer.java
plugin-kafka/src/test/java/org/apache/ranger/authorization/kafka/authorizer/KafkaRangerAuthorizerTest.java
plugin-kafka/src/test/java/org/apache/ranger/authorization/kafka/authorizer/KafkaTestUtils.java
security-admin/src/main/java/org/apache/ranger/elasticsearch/ElasticSearchAccessAuditsService.java
security-admin/src/main/java/org/apache/ranger/elasticsearch/ElasticSearchMgr.java
security-admin/src/main/java/org/apache/ranger/elasticsearch/ElasticSearchUtil.java

Fixes all checkstyle related errors in elasticsearch package for security-admin module
mvn clean install

RANGER-5061: security-admin module(elasticsearch package): update for code readability improvement

---

knox-agent/pom.xml
knox-agent/src/main/java/org/apache/ranger/admin/client/RangerAdminJersey2RESTClient.java
knox-agent/src/main/java/org/apache/ranger/authorization/knox/KnoxRangerPlugin.java
knox-agent/src/main/java/org/apache/ranger/authorization/knox/RangerPDPKnoxFilter.java
knox-agent/src/main/java/org/apache/ranger/services/knox/RangerServiceKnox.java
knox-agent/src/main/java/org/apache/ranger/services/knox/client/KnoxClient.java
knox-agent/src/main/java/org/apache/ranger/services/knox/client/KnoxConnectionMgr.java
knox-agent/src/main/java/org/apache/ranger/services/knox/client/KnoxResourceMgr.java
knox-agent/src/test/java/org/apache/ranger/services/knox/KnoxRangerTest.java
knox-agent/src/test/java/org/apache/ranger/services/knox/RangerAdminClientImpl.java

Fixes all checkstyle related errors in knox-agent module
mvn clean compile verify -Pranger-knox-plugin

RANGER-5036: checkstyle compliance updates - knox-agent

---

kms/src/main/java/org/apache/hadoop/crypto/key/kms/server/KMS.java
kms/src/main/java/org/apache/ranger/kms/metrics/collector/KMSMetricsCollector.java

cherry-pick from https://github.com/apache/ranger/commit/6dd1af9

RANGER-4388: KMS metrics - Implementing best practices

---

ugsync/src/main/java/org/apache/ranger/ldapusersync/process/LdapUserGroupBuilder.java

Revert RDN processing in LdapUserGroupBuilder.
CI

RANGER-5064: checkstyle compliance updates - usersync - LdapUserGroupBuilder

---

README.md

Originally contributed by @mosabua here: https://github.com/apache/ranger/pull/60, re-creating this PR.

RANGER-5106: Remove redundant mvn calls in README

---

dev-support/ranger-docker/.env
dev-support/ranger-docker/Dockerfile.ranger
dev-support/ranger-docker/Dockerfile.ranger-base

Ubuntu version updated from 20.04 to 22.04.
Verified docker setup in Ubuntu 22.04.

RANGER-5138: Docker setup: updated Ubuntu version to 22.04

---

docs/src/site/site.xml
docs/src/site/xdoc/download.xml

Doc updates and updates for apache ranger website.
Verified the links are working.

RANGER-5100: Update Apache Ranger website with 2.6.0

---

.asf.yaml

Notifications should be present at the root level of .asf.yaml file. 
Followed documentation here: https://github.com/apache/infrastructure-asfyaml/blob/main/README.md

RANGER-5165: Update notification settings in .asf.yaml

---

agents-common/src/main/java/org/apache/ranger/plugin/util/RangerRESTClient.java

Retry GET request on server error in RangerRESTClient
(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

RANGER-5201: Retry GET request on server error in RangerRESTClient

---

agents-common/src/main/java/org/apache/ranger/plugin/service/RangerBasePlugin.java

Updated RangerBasePlugin to ensure that references to policyEngine member doesn't cause NPE.
All unit tests pass successfully.

RANGER-5185: fix potential NPE in references to RangerBasePlugin.policyEngine

---

security-admin/src/main/webapp/react-webapp/package-lock.json
security-admin/src/main/webapp/react-webapp/package.json

Ranger: Upgrade axios version 1.7.4 to latest 1.8.4
Manual testing on local machine.

RANGER-5182 : Ranger: Upgrade axios version 1.7.4 to latest 1.8.4

---

kms/src/main/java/org/apache/hadoop/crypto/key/RangerKMSDB.java

[RANGER-5199](https://issues.apache.org/jira/browse/RANGER-5199) : Connection to Ranger KMS DB fails with secure MySQL/maria DB
Fixed the checkstyle issue
1.) Successful build.

RANGER-5199 : Fixing checkstyle issue

---

pom.xml

Bump jacoco plugin to latest released version
CI

RANGER-5228: Bump jacoco to 0.8.13

---

security-admin/src/main/webapp/react-webapp/src/views/AuditEvent/AccessLogs.jsx
security-admin/src/main/webapp/react-webapp/src/views/AuditEvent/AccessLogsTable.jsx

This reverts commit dfaba89d8aa6c00c936357b793b346ea527f86a5.
This changes is not needed.
Tested on my local machine.

Revert "RANGER-5184 : Enhance Access audit to be filtered by Federated user (#560)

---

security-admin/src/main/webapp/react-webapp/src/views/AuditEvent/AdminLogs.jsx
security-admin/src/main/webapp/scripts/views/reports/AuditLayout.js

Missing search Parameter for "XA Group of Users" in Audit Admin logs Tab after pull code base pull from Apache ranger-2.5
Manually tested on local machine

RANGER-5200 : Add search Parameter for XA Group of Users in Audit Admin logs Tab.

---

security-admin/src/main/webapp/react-webapp/config/webpack.dev.config.js
security-admin/src/main/webapp/react-webapp/package-lock.json
security-admin/src/main/webapp/react-webapp/package.json

dependent package that need to be update :
-> @babel/helpers
-> @babel/runtime
-> brace-expansion
-> form-data
-> http-proxy-middleware
-> on-headers
-> webpack-dev-server
1. Applied the patch locally.
2. Verified that the build completed successfully.
3. Checked that the development server started and worked properly.
**Performed sanity testing on the following modules/pages:**
1. Service
2. Policy
3. User, Group, Role
4. Security Zone

RANGER-5283 : Updating library dependencies in Ranger Admin React package-lock.json

---

security-admin/src/main/java/org/apache/ranger/rest/RoleREST.java
security-admin/src/main/webapp/react-webapp/src/views/PolicyListing/AddUpdatePolicyForm.jsx
security-admin/src/main/webapp/react-webapp/src/views/Reports/UserAccessLayout.jsx
security-admin/src/main/webapp/react-webapp/src/views/SecurityZone/SecurityZoneForm.jsx
security-admin/src/main/webapp/react-webapp/src/views/ServiceManager/ServiceForm.jsx

Steps to reproduce:
1) Create user having role as User eg user1
2) Create a policy eg hive and add the above the user, make the user as delegate admin.
3) Login as the user1 and edit the above created policy, try adding role in policy item. Observed the api "/service/roles/roles?roleNamePartial=" giving 400 status.
The patch was tested by validating the new API "/service/roles/lookup/roles/names" from the UI end. The following checks were performed:
1. Validated CRUD operations on policies to ensure all role names are fetched correctly for users with different roles.
2. Validated CRUD operations on services to confirm role names are fetched correctly for different role users.
3. Validated CRUD operations in the Security Zone form to ensure the role names are being fetched properly.
4. …

RANGER-5291 : 'User' role users api '/service/roles/roles' is giving 400 status

---

tagsync/src/main/java/org/apache/ranger/tagsync/process/TagSyncConfig.java
tagsync/src/main/java/org/apache/ranger/tagsync/sink/tagadmin/TagAdminRESTSink.java
tagsync/src/main/java/org/apache/ranger/tagsync/source/atlas/AtlasTagSource.java

Refactor previous commit https://github.com/apache/ranger/commit/24a47ce8a96005a12a8bf9d8b1f09a48a2b8ed94 as check for HA not required
mvn clean install

RANGER-5319: Follow-up: Check for tagsync HA not required

---

agents-common/src/main/java/org/apache/ranger/plugin/policyengine/RangerRequestScriptEvaluator.java
agents-common/src/test/java/org/apache/ranger/plugin/conditionevaluator/RangerRequestScriptEvaluatorTest.java

Replaced iterations with streams equivalents in RangerRequestScriptEvaluator
All tests pass sucessfully.

RANGER-5324: replace iterations with streams in RangerRequestScriptEvaluator

---

pom.xml

Upgrade tomcat to 9.0.109
local build successful, tested ranger admin crud operations.

RANGER-5328: Upgrade Tomcat to 9.0.109

---

kms/src/main/java/org/apache/hadoop/crypto/key/RangerKeyStoreProvider.java
kms/src/main/java/org/apache/hadoop/crypto/key/RangerMasterKey.java

RANGER-5337: A minor fix that  logs the entire exception stack trace instead of simply printing the message. Complete stack trace helps debugging the prod issues.  
- mvn build and UT

RANGER-5337: Exception/Error handling in FIPS MK creation failure flow
